task:
  name: "Kernel Build"
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 4
      memory: 16G

  Build_script:
      - git clone --depth=1 https://github.com/akmacc/android_kernel_realme_x3.git -b msm-4.14 kernel && cd kernel 
      - bash build.sh 
